name: Deploy Web Client to Netlify

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Cache dependencies ⚙️
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 🔀
        run: npm ci

      - name: Build And Deploy to Netlify 🔀
        run: npx nx run web-client:deploy-to-netlify
        env:
          # Netlify env
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.CLIENT_NETLIFY_SITE_ID }}

          # Web Client env
          NEXT_PUBLIC_CLIENT_FIREBASE_CONFIG_JSON: ${{secrets.NEXT_PUBLIC_CLIENT_FIREBASE_CONFIG_JSON}}
          NEXT_PUBLIC_API_KEY: ${{secrets.NEXT_PUBLIC_API_KEY}}
          NEXT_PUBLIC_FIREBASE_VAPID_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY}}
          NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
          NEXT_PUBLIC_HTTP_GRAPHQL_URI: ${{secrets.NEXT_PUBLIC_HTTP_GRAPHQL_URI}}
          NEXT_PUBLIC_WS_GRAPHQL_URI: ${{secrets.NEXT_PUBLIC_WS_GRAPHQL_URI}}
